### ISSUE TITLE
Search Radius for getNearestVertices

### ISSUE THREAD

**Issue by danfran** [Esri/geometry-api-java#107]
Hi,

I have a MultiPoint Geometry that has been loaded with Lat/Lon points (WGS84) and I am trying to use

GeometryEngine.getNearestVertices(g, new Point(0.253437724779, 51.7060144241), searchRadius, 100)

What is the "unit" of searchRadius? degrees?

I am trying different conversions. For example I define searchRadius for 1 Mile like:

earthRadiusInMiles = 3963.2
searchDistanceInMiles = 1
searchRadius = searchDistanceInMiles / earthRadiusInMiles / 0.01 

Is that correct?

**Comment by GISDev01** [comment]
I answered on SO, but here is the same answer for posterity and for future google-ability.

According to this sample, the units of the searchRadius input parameter is in "map units".
Note the very last line of Esri's code sample here:

https://developers.arcgis.com/java/sample-code/nearest-vertices/
    ```
 // maximum search radius panel
    JPanel panelRadius = new JPanel();
    panelRadius.setLayout(new BoxLayout(panelRadius, BoxLayout.X_AXIS));
    panelRadius.setBorder(BorderFactory.createEmptyBorder(5,10,5,5));
    panelRadius.add(new JLabel("Search radius: "));
    txtRadius = new JTextField("20", 10);
    txtRadius.setMinimumSize(new Dimension(30, 20));
    txtRadius.setMaximumSize(new Dimension(30, 20));
    panelRadius.add(txtRadius);
    panelRadius.add(new JLabel(" map units"));

```
http://gis.stackexchange.com/questions/178816/determining-search-radius-for-proximity-search-in-arcgis-api-for-javascript/178851#178851

**Comment by stolstov** [comment]
@danfran The units are the units of the geometry. One degree at equator is approximately 69 miles, so you could use searchRadiusInMiles/69, or to correct your expression:

```searchRadius = searchDistanceInMiles / (earthRadiusInMiles * pi/180)````

**Comment by danfran** [comment]
Hmmm, I am not sure that I am getting the functionality in the right way. I have a set of data on MongoDB that I query in this way:

```
> db.planningPermissionsData.find( { location : { $near : { $geometry : { type : "Point" , coordinates : [ my_lat, my_lng ] } , $maxDistance : 3302 } } } ).count()
108
```

1651 is 1 Mile in metres so 3302 is 2 Miles. GeoJson/WGS84 format.

What I am trying to do is trying to get the same count result with Esri. Anyway when I use both suggestions from @stolstov I get lower counts (74 and 86).

Instead, if I use: 
```
GeometryEngine.geodesicDistanceOnWGS84(point, point2) <= 3302
```

I get the right count.

Is the problem related to the radius only, or the functionality is not meant to be used for that?

**Comment by stolstov** [comment]
@danfran In geometry-api-java, the geometry is planar with the exception of GeometryEngine.geodesicDistanceOnWGS84. The X/Y values are considered on an infinite plane, and all operations are executed based on that assumption.

**Comment by danfran** [comment]
True and unfortunately the planet earth is curved :)

Is there anything in Esri that allows you to do that sort of calculation in a "curved" space?

**Comment by stolstov** [comment]
@danfran It seems that you've wrote a nearest vertex method yourself using geodesicDistanceOnWGS84. Does it work for you?

**Comment by danfran** [comment]
@stolstov yes it looks good comparing different areas. The problem is that to make it efficient you need indexes in memory to skip regions (like for example geohash index or R-Tree algorithm) but I have no time for it at the moment so I am cartesian-ing with Spark and distances :)

**Comment by randallwhitman** [comment]
Idea loosely based on the [utilization of geodesicDistanceOnWGS84 in the trip-discovery sample in the GIS Tools for Hadoop]
(https://blogs.esri.com/esri/arcgis/2013/08/09/vehicle-trip-discovery-with-gis-tools-for-hadoop/):

* determine the maximum degree offset (call it `arcRadius`) for the `searchRadius`, at the relevant latitude, using geodesicDistanceOnWGS84 and ratios;
* reduce the search space with a pseudo-planar distance search of radius `arcRadius`;
* filter the candidate results by true distance, using `geodesicDistanceOnWGS84` (as in comment above).

**Comment by stolstov** [comment]
@randallwhitman The first step then is to use 
```searchRadius = searchDistanceInMiles / (earthRadiusInMiles * pi/180)```
because it is largest at equator.
This would be indeed faster by a large constant factor (unless a spatial index would be somehow used).

Need to be careful to include data around dateline (move query point by +-360, when working close to -180 or +180)
