### ISSUE TITLE
Support convert from/to ST_Geometry

### ISSUE THREAD

**Issue by gisfromscratch** [Esri/geometry-api-java#108]
It would be neat converting from/to ST_Geometry structs as it is the de facto SDE standard.

**Comment by stolstov** [comment]
@gisfromscratch The library supports well-known binary and well-known text formats as in here http://www.opengeospatial.org/standards/sfs

**Comment by gisfromscratch** [comment]
Ok, as you suggest we are going to read/write using well-known binary by using the st_asbinary SQL function.

Right now, we found from your unit tests
OperatorFactoryLocal.getInstance().getOperator(Operator.Type.ImportFromWkb)
OperatorFactoryLocal.getInstance().getOperator(Operator.Type.ExportToWkb)

Maybe those methods can be moved to the GeometryEngine in future releases.

@stolstov

**Comment by randallwhitman** [comment]
Although not in `GeometryEngine` specifically, the Geometry API has `OGCGeometry` with `asBinary` and `fromBinary`.

**Comment by gisfromscratch** [comment]
@randallwhitman  Thank you.
