### ISSUE TITLE
Geometry v1.2.2 release

### ISSUE THREAD

**Issue by randallwhitman** [Esri/geometry-api-java#109]
Are there specific plans for a v1.2.2 release?  I would like to [release v1.2 of spatial-framework-for-hadoop](https://github.com/Esri/spatial-framework-for-hadoop/releases) after the current GeoJSON enhancements are merged.  If it makes sense, I may coordinate that with Geometry v1.2.2 release.

@climbage @alocke @stolstov

**Comment by stolstov** [comment]
I am looking into an issue in the Buffer operation we found locally (buffer may be slightly larger than it should on concave corners). I'd like it to go into 1.2.2.

**Comment by randallwhitman** [comment]
Do you have a target timeframe?
With recently filed https://github.com/Esri/gis-tools-for-hadoop/issues/43 , once we release Spatial-Framework-for-Hadoop v1.2 , people won't hit that exception any more with release JARs.

**Comment by randallwhitman** [comment]
@alocke @climbage @stolstov Do we have a checklist or howto on making a numbered release for Geometry API?  The spatial-framework-for-hadoop release JAR files are rather behind master - need to make a release of spatial-framework whether or not coordinated with Geometry.

**Comment by stolstov** [comment]
@climbage made previous releases for spatial-framework-for-hadoop. We don't make numbered releases otherwise.

**Comment by randallwhitman** [comment]
Just today I made note that there is an interface change - namely a [change in exceptions thrown by OGCGeometry `fromJson` and `fromGeoJson`](https://github.com/Esri/geometry-api-java/commit/d08e90ccabadf00875887352e6aaadd9b99eaa34).  Does this mean that instead of 1.2.2 we need to bump the version number to 1.3 or even 2.0 ?

**Comment by kjkrum** [comment]
I don't know if this project has documented its versioning strategy.  Under Semantic Versioning, this would indeed make it version 2.0.  (Or the change should be saved for 2.0.)

In any case, throwing `Exception` is not very useful to the client, and is perceived as sloppy or lazy.

**Comment by stolstov** [comment]
If I remember correctly the change was to remove dependency on 3rd party libraries from the interface. We'll need to remove this dependency eventually.

**Comment by stolstov** [comment]
@randallwhitman @alocke We need a final testing round.

**Comment by randallwhitman** [comment]
> If I remember correctly the change was to remove dependency on 3rd party libraries from the interface.

In other words, to decouple interface versus implementation.

> We'll need to remove this dependency eventually.

With a version number at which we can make interface change, I guess.
