### ISSUE TITLE
OGCGeometry.equals

### ISSUE THREAD

**Issue by randallwhitman** [Esri/geometry-api-java#110]
Let me know if there is something wrong with the following test, but I think it indicates an issue with `OGCGeometry.equals(Object)`.

``` java
    public void testEquals() {
        Point pt = new Point(15.0, 5.0);
        // For comparison/reference
        assertEquals(new MapGeometry(pt, null), new MapGeometry(pt, null));
        assertEquals(new MapGeometry(new Point(1.0, 2.0), null), new MapGeometry(new Point(1.0, 2.0), null));
        // Test OGCGeometry#equals
        assertTrue(OGCGeometry.createFromEsriGeometry(pt, null).equals(OGCGeometry.createFromEsriGeometry(pt, null)));  // ok
        assertEquals(OGCGeometry.createFromEsriGeometry(pt, null), OGCGeometry.createFromEsriGeometry(pt, null));  // fail
        assertEquals(OGCGeometry.createFromEsriGeometry(new Point(1.0, 2.0), null), OGCGeometry.createFromEsriGeometry(new Point(1.0, 2.0), null));  // fail

    }
```

Maybe need `OGCGeometry.equals(Object)` similar to that of MapGeometry, such as:

``` java
    @Override
    public boolean equals(Object other) {
        if (other == this)
            return true;
        if (other == null  ||  other.getClass() != getClass())
            return false;
        return equals((OGCGeometry)other);
    }
```

(Ran across this issue while writing unit tests for JSON SerDe classes in Spatial-Framework-for-Hadoop.)

**Comment by randallwhitman** [comment]
As mentioned in the incomplete patch, it would then also need `hashCode`.

**Comment by stolstov** [comment]
@randallwhitman I have different fix in the full version. Note that the OGC equals is not same as java equals. Java equals is identity comparison, while OGC equals is topological.

**Comment by stolstov** [comment]
Name is not good. Maybe we should rename OGC equals to Equals(OGCGeometry), and leave java equals(Object) to do Java identity thing.

**Comment by randallwhitman** [comment]
In Java, operator `==` is identity, whereas CustomType.`equals` is conceptual equality.

**Comment by stolstov** [comment]
The ogc equals is slow, and also, probably not what one expects when storing a class in a container, such a hash map. I think ogc equals it should be different from identity equals.
