### ISSUE TITLE
Parse shapefile or GeoJson into MultiPolygon

### ISSUE THREAD

**Issue by terminatorbill** [Esri/geometry-api-java#113]
I am trying to create a Geometry to map the United States. All the data that I have found is of type MultiPolygon. 
I just don't know how to parse either shapefile or GeoJson and map the file into MultiPolygon. Is it possible?
Thank you

**Comment by randallwhitman** [comment]
Samples of parsing GeoJSON in [Spatial Framework for Hadoop](https://github.com/Esri/spatial-framework-for-hadoop):
https://github.com/Esri/spatial-framework-for-hadoop/blob/master/hive/src/main/java/com/esri/hadoop/hive/ST_GeomFromGeoJson.java#L48
https://github.com/Esri/spatial-framework-for-hadoop/blob/master/hive/src/main/java/com/esri/hadoop/hive/serde/GeoJsonSerDe.java#L37

Import from shape byte-buffer:
https://github.com/Esri/spatial-framework-for-hadoop/blob/master/hive/src/main/java/com/esri/hadoop/hive/GeometryUtils.java#L127

**Comment by terminatorbill** [comment]
Thank you very much! I appreciate it!

**Comment by chakravarthyvp** [comment]
I have a GeoJson file of SRID 4326. I'm trying to use ESRI APIs to convert the geojson file to geometries. I won't be using the spatial framework for hadoop. How do I parse a GeoJson file without using this framework?

**Comment by alocke** [comment]
You can call [OperatorImportFromGeoJson](http://esri.github.io/geometry-api-java/javadoc/com/esri/core/geometry/OperatorImportFromGeoJson.html).

```MapGeometry outputGeom = OperatorImportFromGeoJson.local().execute(importFlags, geomType, jsonString, null);```

where GeoJsonImportFlags are
```
public interface GeoJsonImportFlags {
	public static final int geoJsonImportDefaults = 0;
	@Deprecated static final int geoJsonImportNonTrusted = 2;
	/**
	 * If set, the import will skip CRS.
	 */
	public static final int geoJsonImportSkipCRS = 8;
	/**
	 * If set, and the geojson does not have a spatial reference, the result geometry will not have one too, otherwise
	 * it'll assume WGS84.
	 */
	public static final int geoJsonImportNoWGS84Default = 16;	
}
```

**Comment by chakravarthyvp** [comment]
Thanks alocke, Appreciate it...
   My GeoJson is FeatureCollection consisting of features of linestrings, multilinestrings, I see the API does not support FeatureCollection/Features? Any inputs on this?

Varaga

**Comment by alocke** [comment]
Right, FeatureCollection/Feature are not supported at this time. I can talk to my developer about adding it, though.

**Comment by chakravarthyvp** [comment]
That's great, thanks for that.
{code}
MapGeometry ogcGeom = OperatorImportFromGeoJson.local().execute(GeoJsonImportFlags.geoJsonImportDefaults, Type.Unknown, reader.readJson(), null);

fails when Type is specified as 'UnKnown'

at org.json.JSONObject.get(JSONObject.java:498)
	at com.esri.core.geometry.OperatorImportFromGeoJsonLocal.getJSONArray(OperatorImportFromGeoJsonLocal.java:47)
{code}
Would you propose an alternate way?

We are evaluating this API for performing math functions in a streaming solution using flink, to process about a million (coordinates)events/sec with RTT time <100 ms. Have you any benchmarks that you could share ?
Typical functions would be map match based on co-ordinates inside arcs/circles, distance calculations, within polygons/boundaries etc.,

**Comment by alocke** [comment]
It should work with Type.Unknown. What type is your input?

**Comment by chakravarthyvp** [comment]
here is a sample input of geojson

`{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "id": 21.000000, "osm_id": 4040446.000000, "type": "motorway", "name": null, "tunnel": 0, "bridge": 0, "oneway": 1, "ref": "M6;M3", "z_order": 9.000000, "access": null, "service": null, "class": "highway" }, "geometry": { "type": "LineString", "coordinates": [ [ x1, y1],
[x2,y2],
[x3,y3]...
] ] } },
{ "type": "Feature",.....
},
]
`

**Comment by alocke** [comment]
For this input, you will need to wait until FeatureCollection is supported.

**Comment by chakravarthyvp** [comment]
Thanks alocke !

**Comment by RomanIakovlev** [comment]
Any update on supporting the `FeatureCollection`? I've checked on current version, which is 2.1.0, but `FeatureCollection` is still not supported. I understand that since this hasn't been implemented since August 2016 the chance of getting it is quite slim. But it would surely be nice to have it supported.

**Comment by stolstov** [comment]
We won't support FeatureCollection in this library. This should be implemented by the layer above.

**Comment by jgravois** [comment]
Just as an FYI, we maintain an open source Java _Script_ lib for converting between GeoJSON and ArcGIS JSON that supports [Feature Collections](https://github.com/Esri/arcgis-to-geojson-utils/blob/da7d385097b86330dfb1cd8c69270f4110c24e7e/index.js#L370-L375).

https://github.com/Esri/arcgis-to-geojson

A Java port in userland that could more easily be paired with our geometry-api-java would be welcome.
