### ISSUE TITLE
How to load “date” type data in Hadoop using JSON?

### ISSUE THREAD

**Issue by trilokchouhan** [Esri/geometry-api-java#114]
-We have two columns in our feature class 
	1. Field name: Created_Date  Values: 29-01-2015 13:39:06
	2. Field name: Updated_Date  Values: 29-01-2015 13:39:06
-After creating JSON of the same feature class, the values of above date column are getting changed to:
	Created_Date  : 1422538746000
	Updated_Date  : 1422538746000

-	Created a table in Hive using the following script:
Create external table datebhuj (created_date date, last_edited_date  date,created_user string, last_edited_user string, shape as binary)
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
STORED AS INPUTFORMAT 'com.esri.json.hadoop.UnenclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';
-	After loading data into said table, select query giving the following result in date columns:
 	Created_Date  : 1422538746000
	Updated_Date  : 1422538746000
Give us the way to create JSON with correct date type data.

**Comment by randallwhitman** [comment]
FWIW - http://desktop.arcgis.com/en/arcmap/10.3/map/time/supported-field-formats.htm

**Comment by randallwhitman** [comment]
This was probably an issue with Hive or Spatial Framework for Hadoop rather than Geometry.
