### ISSUE TITLE
Problems with OperatorImportFromESRIShape

### ISSUE THREAD

**Issue by kjkrum** [Esri/geometry-api-java#118]
There are several closely related issues with `OperatorImportFromESRIShape` that could be viewed as bugs, design problems, and/or deficiencies in documentation.  It took me an entire day (and the use of a debugger) to figure out how to use `OperatorImportFromESRIShape` in its current form.

First of all, `OperatorImportFromESRIShapeCursor` sets the endianness of the buffer on line 173.  This should be done before the shape type is read on line 67.  As a result, the caller must set the endianness of the buffer themselves.

More insidiously, the shape type is read like this:

`int shapetype = shapeBuffer.getInt(0);`

The assumption here is that the buffer **begins with** the shape to be read, as opposed to being **positioned at** the shape to be read.  If the caller's buffer contains multiple shapes, the caller is forced to slice it and pass in the slice for each shape, resulting in unnecessary object creation.  More practically, the shape type should be read like this:

`int shapetype = shapeBuffer.getInt();`

Unfortunately, this change would not be strictly backward compatible.  If callers are slicing their buffers, then presumably the position of the slice is set to 0, and this would probably work in a backward compatible way.  But only probably.

The javadoc for `OperatorImportFromESRIShape#execute(...)` says nothing about these requirements that the implementation imposes on the caller.

**Comment by stolstov** [comment]
@kjkrum Slicing the buffer would be the way to go here. We need to doc this. Thank you for fixing the byte order issue!

**Comment by willtemperley** [comment]
I was just hit by this one too - but nothing a build from source didn't fix.

I've ended up writing a shapefile reader myself (from reading the spec), implementing `GeometryCursor` because I couldn't figure out how to make `OperatorImportFromESRIShapeCursor` useful.  Happy to contribute if you think being able to directly read .shp files should be part of the API

**Comment by randallwhitman** [comment]
Shapefile reader sounds interesting.  We should decide whether it fits better in geometry-api-java or spatial-framework-for-hadoop.

**Comment by stolstov** [comment]
This should be a sample.
I have a repo with only one sample geometry.
https://github.com/stolstov/samples-geometry-api-java

**Comment by randallwhitman** [comment]
@climbage @smambrose What would you think of including geometry-level samples in the [GIS Tools for Hadoop](https://github.com/Esri/gis-tools-for-hadoop)

**Comment by stolstov** [comment]
@randallwhitman Let me try transferring my repo into Esri org.

**Comment by stolstov** [comment]
Here is the repository for the samples: https://github.com/Esri/samples-geometry-api-java
@willtemperley Would you like to submit your custom GeometryCursor for the shape file as a sample?
I think this could be something as 
```
GeometryCursor gc = new ShapeFileGeometryCursor(filename/stream/etc);
```

**Comment by willtemperley** [comment]
Sure - I created a subproject with the ShapefileGeometryCursor: https://github.com/Esri/samples-geometry-api-java/pull/1
