### ISSUE TITLE
how to set the tolerance in intersection

### ISSUE THREAD

**Issue by ladyfish** [Esri/geometry-api-java#122]
how to set the tolerance value when we execute by intersection

**Comment by stolstov** [comment]
The only way to provide a tolerance is via a spatial reference parameter. The tolerance is a part of spatial reference, but we have not provided a way to create a spatial reference with a custom tolerance. The tolerance is hardcoded to the spatial reference well known ID and is about 1 mm in the units of the spatial reference. Also, you can pass a null spatial reference parameter, in which case tolerance would be some small value calculated from the geometry coordinates.
