### ISSUE TITLE
Remove use of JSONObject.getNames for Android

### ISSUE THREAD

**Issue by stolstov** [Esri/geometry-api-java#128]
From #124 

Problem
Google included their own slightly incompatible version of org.json:json in Android, and the Android Gradle plugin automatically excludes dependencies on any other version. Google's implementation of JSONObject is missing the static method getNames(JSONObject). ProGuard minimization detects the missing method and the build fails:

 Warning: com.esri.core.geometry.JSONObjectEnumerator: can't find referenced method 'java.lang.String[] getNames(org.json.JSONObject)' in library class org.json.JSONObject

**Comment by stolstov** [comment]
@kjkrum Could you test master branch if it works?

**Comment by kjkrum** [comment]
ProGuard no longer has a problem with it.  But I can't find a sample of GeoJSON that doesn't trigger this exception at `OperatorImportFromGeoJsonLocal` line 194:

	// According to the spec, a GeoJSON object must have both a type and
	// a coordinates array
	if (!b_type_found || (!b_coordinates_found && !skip_coordinates)) {
		throw new IllegalArgumentException("invalid argument");
	}

Maybe I'm using it wrong.

	OperatorImportFromGeoJson.local().execute(0, Geometry.Type.Unknown, GEOJSON, null);

**Comment by stolstov** [comment]
@kjkrum The call looks correct. There are unit tests for geojson import export in the TestImportExport.java. Could you share a string that fails for you?

**Comment by kjkrum** [comment]
It works with a string from one of the unit tests.  I just wasn't clear on what was supposed to be in the string.
