### ISSUE TITLE
Buffering of polyline fails with an NPE when 

### ISSUE THREAD

**Issue by willtemperley** [Esri/geometry-api-java#129]
I'm getting an NPE when buffering a polyline.

This happens when the Bufferer has decided the polyline is degenerate in `Bufferer.bufferPolylinePath` 

Quick-and-dirty fix here by removing the reference to the null `m_geometry`:

https://github.com/willtemperley/geometry-api-java/commit/70cfd8dcf63967a4f1a2d2bebb79094b97b0398b

**Comment by stolstov** [comment]
@willtemperley Thank you for reporting this. The fix should be
Polygon resultPolygon = new Polygon(point.getDescription());
Do you have a small repro case? The geometry could be saved to json file or string using OperatorFactoryLocal.

**Comment by willtemperley** [comment]
I created the simplest test case I could which reproduced the problem - failing test here:
https://github.com/Esri/geometry-api-java/pull/130

**Comment by stolstov** [comment]
@willtemperley Great! Thank you for the fix!

**Comment by willtemperley** [comment]
A pleasure, cheers
