### ISSUE TITLE
geometry-api-java use non free json.org

### ISSUE THREAD

**Issue by puntogil** [Esri/geometry-api-java#131]
Hi,
Fedora [1] is a popular distribution of the Linux operating system, and
we wish to include the latest version of geometry-api-java in our OS.
Fedora only contains Free and Open Source licensed works.

Your project is licensed under Apache License Version 2,
but your code use from json.org under Douglas Crockford’s bad licence, and is non-free [2].
Such usage restriction makes the license incompatible with The Open Source Definition and
The Free Software Definition. Because geometry-api-java binary distribution includes this software,
it effectively becomes proprietary software itself.

You may also comment that the json.org license is valid for You [3] but for many Linux distributions it is not acceptable.

Hoping in the future to be able to use geometry-api-java in Fedora, without having to run into this problem.

Please try to replace it with one of the many free alternatives.

Thanks in advance
Regards

[1] https://fedoraproject.org/wiki/Fedora_Project_Wiki

[2]
https://wiki.debian.org/qa.debian.org/jsonevil
http://www.sonatype.com/people/2012/03/use-json-well-youd-better-not-be-evil/
http://tanguy.ortolo.eu/blog/article46/json-license

[3] http://www.apache.org/legal/resolved.html#json

**Comment by randallwhitman** [comment]
This is great news that Fedora would like to package the Geometry API for Java.

> Because geometry-api-java binary distribution includes [json.org] software ...

Wouldn't a Linux distro build the library from scratch, rather than ship a pre-compiled binary/jar file?

**Comment by stolstov** [comment]
Internally we don't access this class directly, but through an abstract JSONReader. So it's easy to remove, but it would be a breaking API change.

**Comment by puntogil** [comment]
Hi
Thanks for your interest
> Wouldn't a Linux distro build the library from scratch, rather than ship a pre-compiled binary/jar file?

yes, we build all libraries from their sources
https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#No_inclusion_of_pre-built_binaries_or_libraries

> Internally we don't access this class directly, but through an abstract JSONReader. So it's easy to remove, but it would be a breaking API change.

maybe, you might consider the approach used for https://github.com/skyscreamer/JSONassert/issues/44

Thanks
Regards

**Comment by stolstov** [comment]
@puntogil Removing this dependency would be a breaking API change regardless of the approach.

**Comment by randallwhitman** [comment]
@puntogil Can you provide a merge/pull request like that of skycreamer?

**Comment by randallwhitman** [comment]
@puntogil https://github.com/Esri/geometry-api-java/releases/tag/v2.0.0
