### ISSUE TITLE
The new release v2.0.0

### ISSUE THREAD

**Issue by riyafa** [Esri/geometry-api-java#140]
Dear all,

This is only a question and not really an issue. I would like to know when a new release of the api to be expected with the recent changes which includes the fix for the license issue.

I am using this api on a project in AsterixDB and am looking forward to a new release so that my changes could be merged in AsterixDB master.

**Comment by randallwhitman** [comment]
Are you able to build off the branch meanwhile?

**Comment by riyafa** [comment]
Yes I am currently developing using the api as an external dependency in maven that is I use the built jar file.

**Comment by randallwhitman** [comment]
We have started drafting v2.0.0 release.

**Comment by riyafa** [comment]
Thank you and looking forward to it.

**Comment by stolstov** [comment]
@riyafa It is out there, have you tried it?

**Comment by riyafa** [comment]
Sorry about the ignorance. Am I to call the dependency as follows?
```
<dependency>
            <groupId>com.esri.geometry</groupId>
            <artifactId>esri-geometry-api</artifactId>
            <version>2.0.0</version>
        </dependency>
```
This does not seem to work for me. Am I doing anything wrong? If so kindly correct me.

**Comment by randallwhitman** [comment]
@stolstov I have not yet had the chance to rebuild v2.0.0 with #143.

@riyafa It is not yet deployed to maven central.

**Comment by randallwhitman** [comment]
Released rebuilt v2.0.0 on GigHub.
Remaining to-do is maven central.

**Comment by riyafa** [comment]
Thank you for letting me know. We will await the release in maven.

**Comment by julianhyde** [comment]
Sorry to nag, but any ETA on the maven central release? I'd love to push https://issues.apache.org/jira/browse/CALCITE-1968 to Calcite's master branch before 1.14 (due to freeze in about a week) but can't do that until the artifacts are in maven central.

**Comment by randallwhitman** [comment]
`mvn clean deploy -P release 2>&1`
```
[ERROR] Rule failure while trying to close staging repository with ID "comesri-1046".
[ERROR] 
[ERROR] Nexus Staging Rules Failure Report
[ERROR] ==================================
[ERROR] 
[ERROR] Repository "comesri-1046" failures
[ERROR]   Rule "signature-staging" failures
[ERROR]     * Missing Signature: '/com/esri/geometry/esri-geometry-api/2.0.0/esri-geometry-api-2.0.0-javadoc.jar.asc' does not exist for 'esri-geometry-api-2.0.0-javadoc.jar'.
[ERROR]     * Missing Signature: '/com/esri/geometry/esri-geometry-api/2.0.0/esri-geometry-api-2.0.0-sources.jar.asc' does not exist for 'esri-geometry-api-2.0.0-sources.jar'.
[ERROR]     * Missing Signature: '/com/esri/geometry/esri-geometry-api/2.0.0/esri-geometry-api-2.0.0.pom.asc' does not exist for 'esri-geometry-api-2.0.0.pom'.
[ERROR]     * Missing Signature: '/com/esri/geometry/esri-geometry-api/2.0.0/esri-geometry-api-2.0.0.jar.asc' does not exist for 'esri-geometry-api-2.0.0.jar'.
[ERROR] 
[ERROR] 
[ERROR] Cleaning up local stage directory after a Rule failure during close of staging repositories: [comesri-1046]
[ERROR]  * Deleting context 58080076bf2b1.properties
[ERROR] Cleaning up remote stage repositories after a Rule failure during close of staging repositories: [comesri-1046]
[ERROR]  * Dropping failed staging repository with ID "comesri-1046" (Rule failure during close of staging repositories: [comesri-1046]).

Waiting for operation to complete......

[ERROR] Remote staging finished with a failure: Staging rules failure!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by julianhyde** [comment]
You might need to supply `-Dgpg.passphrase=thephrase`.

**Comment by randallwhitman** [comment]
Was a requirement added more recently than [Geometry v1.2.1](https://mvnrepository.com/artifact/com.esri.geometry/esri-geometry-api/1.2.1)?

**Comment by julianhyde** [comment]
Seems like signing was added for 1.2: https://github.com/Esri/geometry-api-java/commit/5324ae50d61d308708581b2a62233d16ff9d3bf5.

Anyway,  http://central.sonatype.org/pages/working-with-pgp-signatures.html might help. I think I always need -Dgpg.passphrase when I deploy to maven central.

**Comment by randallwhitman** [comment]
Will ask @climbage who prepared the previous releases.

**Comment by climbage** [comment]
Binaries have been signed and released. Should show up in the maven repositories within an hour or two. 

oss.sonatype.org requires that binaries placed in their open source nexus are signed - that was the only step you were missing @randallwhitman.

**Comment by julianhyde** [comment]
Thanks! I've committed partial OpenGIS support in Apache Calcite based on this. Will be in Calcite 1.14. https://issues.apache.org/jira/browse/CALCITE-1968

**Comment by GISDev01** [comment]
```
<dependency>
    <groupId>com.esri.geometry</groupId>
    <artifactId>esri-geometry-api</artifactId>
    <version>2.0.0</version>
</dependency>
```
is working well for me. I think this can be closed. 
Ref: https://mvnrepository.com/artifact/com.esri.geometry/esri-geometry-api/2.0.0
