### ISSUE TITLE
GeometryEngine.intersect does not find intersection 

### ISSUE THREAD

**Issue by Akshay-Thakare** [Esri/geometry-api-java#141]
While trying to find intersection between two polylines

Polyline t = new Polyline();
t.startPath(21.041040, 76.720243);
t.lineTo(21.040782, 76.722739);

Polyline e = new Polyline();
e.startPath(21.040061, 76.722679);
e.lineTo(21.040812, 76.722709);

// the below statement returns true
boolean intersects = OperatorIntersects.local().execute(t,e,null,null);

// while
Geometry out = OperatorIntersection.local().execute(t,e,null,null);

// the above statement does not return any point / path
// {"paths":[]}

Could you please suggest how to get the intersection point.

**Comment by stolstov** [comment]
@Akshay-Thakare Try using overloaded method with the dimensionMask. If you want only points in the intersection, dimensionMask = 1. For any type of intersection, pass 7.
