### ISSUE TITLE
Add Geometry::estimateMemorySize() API

### ISSUE THREAD

**Issue by mbasmanova** [Esri/geometry-api-java#156]
I'm using ESRI Geometry API to provide geospatial query support in Presto ( https://prestodb.io/ ) and I need to calculate how much memory individual Geometry objects occupy. I'm using ClassLayout.parseClass to compute the base size of an object and then add on sizes of arrays, lists, etc. I need to be able to write this code:

```
private static final int MULTI_POINT_IMPL_INSTANCE_SIZE = ClassLayout.parseClass(MultiPointImpl.class).instanceSize();
private static final int MULTI_PATH_IMPL_INSTANCE_SIZE = ClassLayout.parseClass(MultiPathImpl.class).instanceSize();
```

(see https://github.com/prestodb/presto/pull/9474/files#diff-ac9e6026ae8bd12a435b09b61a5cc0fa)

But I can't because MultiPointImpl and MultiPathImpl classes are package private. 

Would it be possible to make them public?

**Comment by stolstov** [comment]
If are working on this, would you be willing to add an abstract method to the  Geometry class and other classes as needed called estimateMemorySize() that returns the size of the geometry instance in memory?

**Comment by stolstov** [comment]
```
      /**
      * Calculates approximate size of the structure in memory including all the data it holds.
      * @return size in bytes.
      */
```

**Comment by mbasmanova** [comment]
@stolstov Sergey, thanks for a quick response. Absolutely, I'd be happy to work on a PR to add estimateMemorySize() to the Geometry objects. Is there anything I should be aware of/read about before starting?

**Comment by stolstov** [comment]
@mbasmanova That would be great if you could add those methods. Please, use same formatting as we do, and read CONTRIBUTING.md (which is basically a link to this https://github.com/esri/contributing) for the legal info.

**Comment by mbasmanova** [comment]
@stolstov Sergey, PR #157 adds the new API. Would you take a look?

**Comment by stolstov** [comment]
@alocke Could you verify this?

**Comment by alocke** [comment]
Yes, I will.

**Comment by mbasmanova** [comment]
@alocke Annette, I'd like to use the new API in Presto https://prestodb.io/ . Do you have an idea of when a new release might be available?

**Comment by alocke** [comment]
@mbasmanova Thank you. Verified.

**Comment by mbasmanova** [comment]
@alocke Thank you, Annette! What are the next steps?

**Comment by alocke** [comment]
@mbasmanova Thank you!
@randallwhitman What are the next steps?

**Comment by randallwhitman** [comment]
See https://github.com/Esri/geometry-api-java/releases/tag/v2.1.0

**Comment by mbasmanova** [comment]
@randallwhitman Randall, thanks for releasing the new version. Will it appear on Maven Central automatically within a short period of time or is something else necessary to make this happen?

https://mvnrepository.com/artifact/com.esri.geometry/esri-geometry-api

**Comment by randallwhitman** [comment]
I ran `mvn deploy -Prelease -DperformRelease=true`; we'll have to see if the files propagate versus if I get stuck like - https://github.com/Esri/spatial-framework-for-hadoop/issues/123

**Comment by mbasmanova** [comment]
@randallwhitman Randall, I see 2.1.0 release in Maven central: https://mvnrepository.com/artifact/com.esri.geometry/esri-geometry-api/2.1.0

Thank you so much!
