### ISSUE TITLE
OGCGeometry#asText outputs polygon shell in counterclockwise order

### ISSUE THREAD

**Issue by mbasmanova** [Esri/geometry-api-java#160]
I'm seeing that covering WKT to OGCGeometry and then back to WKT generates a different value. Specifically, the outer ring of a polygon is generated in counterclockwise order which seems wrong. Why is that? Can this be fixed?

Here is a test case illustrating the problem:

```    
   @Test
    public void test()
    {
        String wkt = "POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))";
        assertEquals(OGCGeometry.fromText(wkt).asText(), wkt);
    }

java.lang.AssertionError: expected [POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))] but found [POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))]
Expected :POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))
Actual   :POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))
```

CC: @jijichen

**Comment by stolstov** [comment]
@mbasmanova We consider WKT to be a format of the OGC standard, that specifies that the exterior rings are counterclockwise and the interiors are clockwise.

**Comment by stolstov** [comment]
See OGC spec OGC 06-103r4, 6.1.11.1 Description:

> A Polygon is a planar Surface defined by 1 exterior boundary and 0 or more interior boundaries. Each interior
boundary defines a hole in the Polygon. A Triangle is a polygon with 3 distinct, non-collinear vertices and no
interior boundary.

> The exterior boundary LinearRing defines the “top” of the surface which is the side of the surface from which the
exterior boundary appears to traverse the boundary in a counter clockwise direction. The interior LinearRings will
have the opposite orientation, and appear as clockwise when viewed from the “top”

**Comment by mbasmanova** [comment]
@stolstov Sergey, thanks for clarifying. When generating WKT, ESRI library uses definition from OGC (polygon shell vertexes are listed counterclockwise), but when reading WKT ESRI handles either case. In the shapefile, however, the library uses clockwise order for polygon shells. Is this correct?

https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf
```
Vertices of rings defining
holes in polygons are in a counterclockwise direction. Vertices for a single, ringed
polygon are, therefore, always in clockwise order. 
```

**Comment by stolstov** [comment]
@mbasmanova That's correct, the polygon in the esri shape should have clockwise exterior rings and counterclockwise holes, there should be no self intersections. If polygons do have self intersections or incorrect ring order, they can be fixed with the OperatorSimplify before writing to the esri shape file.

**Comment by mbasmanova** [comment]
@stolstov Sergey, thanks for confirming. I have a follow-up question. I didn't know about OperatorSimplify. Which algorithm does it use to transform the geometry?

**Comment by stolstov** [comment]
@mbasmanova OperatorSimplify resolves all self intersections and then rebuilds the polygon taking into account the polygon's fill mode to determine interior of the polygon. The default fill mode is [even-odd](https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule). So if one draws side by side the non-simple polygon with the even-odd fill mode, then draws the simplified polygon, both should look the same.

If you also wish that the result polygon was valid for the OGC spec (it is more restrictive than esri's), use OperatorSimplifyOGC. The OGC spec puts certain restrictions on how rings can touch other rings and does not allow self-tangent rings.

**Comment by mbasmanova** [comment]
@stolstov Sergey, thank you so much for this info. It is very helpful.
