### ISSUE TITLE
Add function to compute centroid

### ISSUE THREAD

**Issue by mbasmanova** [Esri/geometry-api-java#167]
I cannot find an API to compute centroid of a geometry and I noticed that ST_Centroid function in spatial-framework-for-hadoop returns centroid of the bounding box and not of the geometry itself. 

https://github.com/Esri/spatial-framework-for-hadoop/wiki/UDF-Accessors#st_centroid

I implemented ST_Centroid function in Presto using formulas from https://en.wikipedia.org/wiki/Centroid and now wondering if it makes sense to add the same to this library.

https://github.com/mbasmanova/presto/blob/master/presto-geospatial/src/main/java/com/facebook/presto/plugin/geospatial/GeoFunctions.java#L160

**Comment by randallwhitman** [comment]
@alocke @stolstov If a centroid function were contributed to Geometry, I'd be eager to utilize it for ST_Centroid in Spatial Framework for Hadoop.

**Comment by mbasmanova** [comment]
@stolstov Sergey, how would you feel about adding centroid function to the library?

**Comment by stolstov** [comment]
@mbasmanova Would like to contribute? 

The following signature would be preferable:

```
public abstract class OperatorCentroid2D extends Operator {
	@Override
	public Type getType() {
		return Type.Centroid;
	}

	public abstract Point2D execute(Geometry geometry,
			ProgressTracker progressTracker);

	public static OperatorCentroid2D local()
}
```

**Comment by mbasmanova** [comment]
@stolstov Sure, I'd be happy to contribute an implementation of centroid. Thanks for the tip about how to get started. I put something together at #169 . Would you take a look?

**Comment by alocke** [comment]
Verification
* TestCentroid
* TestOGCCentroid
