### ISSUE TITLE
Having an issue where sometimes L.esri undefined (Question)

### ISSUE THREAD

**Issue by rnonajr** [Esri/geometry-api-java#188]
Hi,

I've never worked with esri and right now I'm taking over a project using esri and I am encountering an issue that doesn't always occur.  

Sometimes when a user attempts to open a map, the map area remains grey and in the console I can see the error message "Cannot read property 'featureLayer' of undefined" 

`map = L.map("map").setView(JSON.parse(result.CenterOfTheMap), result.ZoomLevel);
 
           var zipcodes = L.esri.featureLayer({
                url: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_ZIP_Codes/FeatureServer/0',
                zoom: 18,
                simplifyFactor: 0.35,
                precision: 5,
                fields: ['FID', 'ZIP', 'PO_NAME'],
                style: function (feature) {
                    if (DoesItExists(feature.properties.ZIP)) {
                        return {
                            color: getBorderColor(feature.properties.ZIP), //'#A9A9A9',
                            weight: 1,
                            fillOpacity: 0.7,
                            fillColor: getColor(feature.properties.ZIP)
                        }
                    }
                    else {
                        return {
                            color: '#A9A9A9',
                            weight: 0.2
                        }
                    }
                }
            }).addTo(map);`

When I Watch the L variable it is defined but L.esri is undefined.

As I said, this issue doesn't always manifest itself and I'm not sure what / where I should be looking for a solution.  Any help would be appreciated.

Thanks
Bob

**Comment by randallwhitman** [comment]
The code snippet looks more like JavaScript than Java or Scala.
The Esri geometry-api-java is for JVM not JS/EcmaScript.

**Comment by rnonajr** [comment]
Sorry, can this be moved to a JavaScript section?

**Comment by jgravois** [comment]
@rnonajr please post in https://github.com/Esri/esri-leaflet/issues. I'm happy to try and help.

**Comment by rnonajr** [comment]
Thanks @jgravois, the question has been moved.
