### ISSUE TITLE
Is there a way to compute a concave hull?

### ISSUE THREAD

**Issue by mbasmanova** [Esri/geometry-api-java#191]
`OGCGeometry#convexHull` computes convex hull, but is there a way to compute concave hull (e.g. https://postgis.net/docs/ST_ConcaveHull.html)

**Comment by stolstov** [comment]
@mbasmanova There is no such method implemented in the library.

**Comment by mbasmanova** [comment]
@stolstov Thank you for a quick reply, Sergey.
