### ISSUE TITLE
Null pointer exception when computing convex hull with GeometryCollection type

### ISSUE THREAD

**Issue by yuyongyang800** [Esri/geometry-api-java#194]
Suppose I have a GeometryCollection with multiple polygons. The convexHull() method in OGCConcreteGeometryCollection class throws an exception:

java.lang.NullPointerException
	at com.esri.core.geometry.ogc.OGCConcreteGeometryCollection.convexHull(OGCConcreteGeometryCollection.java:447)
	
In this case, the resultGeom object is initialized as null. The mp variable is also empty, since there are no point type geometry objects. This leads to an empty test on the null value in Line 447. Is this behavior correct? Could someone check this section of code? Thanks.

**Comment by stolstov** [comment]
@yuyongyang800 Thank you for reporting. I'll take a look.

**Comment by yuyongyang800** [comment]
Thanks for the fix.

**Comment by yuyongyang800** [comment]
Hi Sergey, do you have an idea when version 2.2.1 will be released?

**Comment by stolstov** [comment]
@randallwhitman Randall, can we make a release?

**Comment by randallwhitman** [comment]
Making note, but won't get to it immediately
