### ISSUE TITLE
GeometryCursor:: estimateMemorySize

### ISSUE THREAD

**Issue by tdcmeehan** [Esri/geometry-api-java#198]
Similar to #156, we would like to investigate whether it's possible to add a similar API to `GeometryCursor` to enable us to estimate the memory size for long running operations involving GeometryCursors.  For example, it would be nice to get a point in time estimate of how much memory `OperatorUnionCursor` is using, for similar reasons as stated in #156.

It would have the same signature as what is found in OGCGeometry:

```java
GeometryCursor unioningCursor =  OperatorUnion.local().execute(input, null, null);
// ...
System.out.println(unioningCursor.estimateMemorySize());
```

Are there any objections to adding such an API?

**Comment by stolstov** [comment]
@tdcmeehan You would only be able to estimate how much memory it was using after completion of operation.

**Comment by tdcmeehan** [comment]
@stolstov thank you for the quick reply.  I may not be understanding, but could we not keep track of the memory usage via added state on the cursor, and update it whenever the object's state changes?  For example, after `add_geom` in `OperatorUnionCursor`, we add the memory usage of the added `Bin_type`.

**Comment by stolstov** [comment]
You could feed OperatorUnion one geometry at a time using ListeningGeometryCursor if this is something you are looking for.

**Comment by tdcmeehan** [comment]
@stolstov that is correct, and indeed that is what I'm planning on doing.  However, my understanding is that internally `OperatorUnionCursor` is batching the constituent geometries before performing the union.  So what I'm looking for is a way to get an estimate as to how much memory is being used in that process, before `next()` is called.  As above, I thought it should be possible to incrementally adjust the estimate of memory usage whenever a mutation occurs.

**Comment by stolstov** [comment]
@tdcmeehan Could you explain the pattern how you are planning to use this?

Maybe you should do external batching. For anything large you may want to batch geometries spatially.
