### ISSUE TITLE
Buffer Polyline not honoring point order

### ISSUE THREAD

**Issue by FlushedCrusher** [Esri/geometry-api-java#202]
Hello,

I am attempting to buffer a polyline [[[45, 45], [13, 13], [47,47]]]
but the buffer keeps returning a polygon that appears to be the buffer of  [[[47, 47], [45, 45], [13, 13]]].

    public static Polyline generatePolyline(List<Position> positions) {
        Polyline line = new Polyline();
        line.startPath(positions.get(0).getLon(), positions.get(0).getLat());
        positions.stream().skip(1).forEach((position) -> {
            line.lineTo(position.getLon(), position.getLat());
        });
        return line;
    }

    public static OGCGeometry generateOGCGeometry(Polyline line, double distance) {
        OperatorBuffer buffer
                = (OperatorBuffer) OperatorFactoryLocal.getInstance().getOperator(Type.Buffer);
        Geometry result = buffer.execute(line, spatialReference, distance / 60, null);
        Polygon poly = (Polygon) (result);
        return new OGCPolygon(poly, spatialReference);
    }

This is rattling my brain, I must be doing something fundamentally wrong.

I even tried breaking the legs of the polyline in to pairs, buffering the two point polylines, and then combining the results with a union of each leg.

This had the same result.

Help is appreciated, or if there is another forum for this kind of question someone can point me to.

 @Thanks!

**Comment by alocke** [comment]
Hi,
Can you explain what you mean by " a polygon that appears to be the buffer of [[[47, 47], [45, 45], [13, 13]]]"?

**Comment by FlushedCrusher** [comment]
![buffer](https://user-images.githubusercontent.com/21090677/46227625-a6342e80-c314-11e8-8ba4-102a27137aa1.png)

Hope this helps explain.

**Comment by alocke** [comment]
I see. What spatial reference are you using? What is the buffer distance?

**Comment by alocke** [comment]
I mean, what is the spatial reference of the map shown in your picture?

**Comment by FlushedCrusher** [comment]
SpatialReference spatialReference = SpatialReference.create(4326);

The buffer unit is another thing that I have had trouble finding. The goal is to buffer in nautical miles; in this case 1.

**Comment by alocke** [comment]
The points (45,45), (13,13), and (47,47) are all on the same line. That is why the buffer looks like it does. 
The buffer unit is the unit of the spatial reference of the data. Does that make sense?

**Comment by FlushedCrusher** [comment]
Ahh, the buffer does make sense now that you have pointed that out.

Do you know a good resource on how I might solve my NM -> spatial reference unit conversion?
