### ISSUE TITLE
Enable support for 3D functions

### ISSUE THREAD

**Issue by omlstreaming** [Esri/geometry-api-java#203]
For what I learned from the WIKI you support only 2D geometry function. However, most of the APIs you have should work also on 3D Points. Just, all the methods are private in general, and when you can work around using the generic interface Point,  then it is cast to a 2D point (e.g. distance). 

Is there any plan to support 3D Points directly? what is the current main limitation that does not allow for such feature to be available?

**Comment by stolstov** [comment]
@omlstreaming You can have 3D geometries. Create a point as with "new Point(x, y, z)", or call point.setZ(z) to add z component to existing instance. However, relational and topological operations will be performed in xy plane. Which methods do you want to be made public?

**Comment by stefanobortoli** [comment]
@stolstov I would like indeed to have relational and topological operations to be computed on 3D points. For what I can see, you support 3DEnvelope, which is not bad to start. But to have contains, intersects, overlaps etc. on polihedron would help a lot. However, I would like to have for example the geodesic distance on 3D Points, and some support to define polyhedron. I'm a bit confused on where to start with the current version of the library on these topics, even thou it supports 3D points.

**Comment by stolstov** [comment]
@stefanobortoli The library does not have any topological or relational operations in 3D.

**Comment by stefanobortoli** [comment]
@stolstov I realized that. I was wondering whether that can change, in the future. :-) For the moment I am using georegression for some simple things.

**Comment by icemagno** [comment]
Why have you 3D geometries and can't make any operation in 3D space? This api have no use to me.
