### ISSUE TITLE
Include the size of geometry accelerator in OGCGeometry#estimateMemorySize

### ISSUE THREAD

**Issue by mbasmanova** [Esri/geometry-api-java#204]
We are seeing acceleration delivering significant performance improvements in spatial joins in Presto:  https://github.com/prestodb/presto/issues/11953 . We'd like to start using this and therefore need to update `OGCGeometry#estimateMemorySize` to account for memory used by the accelerator.

I'll make a PR if there are no objections.

CC: @stolstov

**Comment by stolstov** [comment]
@mbasmanova Sure, please do.

**Comment by mbasmanova** [comment]
@stolstov Thank you!

**Comment by stolstov** [comment]
Note: Public interface change: new abstract method ScanCallback.estimateMemorySize

**Comment by stolstov** [comment]
Note, the change to a public interface was removed.
