### ISSUE TITLE
Need a release with acceleration fixes/enhancements?

### ISSUE THREAD

**Issue by mbasmanova** [Esri/geometry-api-java#208]
Folks, would it be possible to make a release with acceleration changes #206 and #207?

CC: @stolstov @randallwhitman @jagill

**Comment by stolstov** [comment]
@mbasmanova Could you verify issues, associated with those PRs?

**Comment by mbasmanova** [comment]
@stolstov Sergey, I re-built Presto with a snapshot of ESRI library from master and re-run spatial join query with acceleration enabled. The query ran fast and results are identical to non-accelerated version. I think we are good to go.

CC: @jagill

**Comment by mbasmanova** [comment]
@stolstov Sergey, would it be possible to make a release this week?

**Comment by randallwhitman** [comment]
Per method added to interface, we need to determine which release number this should be:
* 2.2.2
* 2.3.0
* 3.0.0

**Comment by stolstov** [comment]
@mbasmanova Is it possible to refactor and remove this method?
https://github.com/Esri/geometry-api-java/blob/master/src/main/java/com/esri/core/geometry/SimpleRasterizer.java#L65

**Comment by mbasmanova** [comment]
@stolstov Sure. Here is the change: #209

**Comment by stolstov** [comment]
https://github.com/Esri/geometry-api-java/releases/tag/v2.2.2

**Comment by mbasmanova** [comment]
@stolstov Thank you, Sergey!

**Comment by randallwhitman** [comment]
https://mvnrepository.com/artifact/com.esri.geometry/esri-geometry-api/2.2.2
