### ISSUE TITLE
Does a.contains(b) use b's acceleration?

### ISSUE THREAD

**Issue by jagill** [Esri/geometry-api-java#210]
We are considering a case where we have an accelerated `b`, and many (generally not accelerated) `a`s.  Does this operation get any performance benefit from `b`'s acceleration?  Does the answer depend on whether `a` is accelerated?

cc: @mbasmanova

**Comment by stolstov** [comment]
@jagill It would help when that relation is false most of the times, and that the envelope of a is often completely inside or completely outside of b.
