### ISSUE TITLE
How can i move a point by distance and direction?

### ISSUE THREAD

**Issue by KehwZwei** [Esri/geometry-api-java#211]
I want to move a point by distance and direction. witch api can do this thing?

**Comment by alocke** [comment]
Hi, you can use Transformation2D. Here is a simple example.
```
Point point = new Point(0, 0);
Transformation2D transformation = new Transformation2D();

// This will move the x-coordinate by 2 units and the y-coordinate by 2 units.
transformation.setShift(2, 2);
point.applyTransformation(transformation);

// Now the coordinates of the point are (2, 2)

// This will rotate the point
transformation.setRotate(Math.PI/ 4);
point.applyTransformation(transformation);

// Now the coordinates of the point are (0, sqrt(8))
```
There is also Transformation3D if your point has z-values. Point2D and Point3D have similar methods. 

I hope this helps.

**Comment by icemagno** [comment]
Can't find Transformation3D  [here](http://esri.github.io/geometry-api-java/javadoc/allclasses-noframe.html)

**Comment by stolstov** [comment]
@icemagno I've submitted a PR to make the Transformation3D public.

**Comment by KehwZwei** [comment]
Thanks for the example.
