### ISSUE TITLE
Need below function to execute in hive

### ISSUE THREAD

**Issue by kullaibigdata** [Esri/geometry-api-java#215]
Hi I am very new to spatial function . As I searched on google I find out the ESRI github code and I Clone that code and I add the dependencies and it's working fine.

Now below spatial functions we are not able to find out . Can you please share below spatial hive UDF code.
 
st_closestpoint
st_distancesphere
st_linesubstring
st_linemerge
st_covers
st_makeline

If you have any alternatives spatial function kindly please share for the same.

Thanks & Regards,
Kullaireddy N.

**Comment by randallwhitman** [comment]
Esri/spatial-framework-for-hadoop#159
