### ISSUE TITLE
why i get a negative value from calculateArea2D

### ISSUE THREAD

**Issue by muyline** [Esri/geometry-api-java#220]
`String jsonString = "{\"rings\":[[[364516.41281089187,2945011.8117792667],[364514.014267579,2945015.3595735505],[364509.3666061158,2945024.6547005093],[364499.1500403187,2945033.119709451],[364477.9477365769,2945037.4976217523],[364445.3943136241,2945027.3202494406],[364401.5153452095,2944996.034833719],[364354.95368071407,2944955.3544456344],[364305.96603746613,2944902.76060981],[364261.6109661896,2944848.6382280607],[364227.6250213513,2944798.298213605],[364207.4572296524,2944751.503347872],[364195.47774088936,2944706.5523396526],[364193.1096705113,2944666.6713026995],[364197.9257659773,2944628.1295071375],[364209.1600886023,2944600.8461381933],[364221.2035607299,2944574.349774433],[364239.6803495083,2944552.6603936534],[364261.09606177727,2944531.246543075],[364288.6484939974,2944511.507332137],[364315.4700657015,2944494.3679230586],[364349.97013108234,2944477.4578938526],[364381.7095053467,2944462.7910057907],[364417.914291368,2944450.418896289],[364454.3502209685,2944440.6315971394],[364496.86839157564,2944435.4451232376],[364534.720283814,2944433.23882397],[364571.52414225717,2944435.27022231],[364613.5805156245,2944437.8853096287],[364646.646295413,2944441.588898016],[364684.57598671963,2944449.015671534],[364715.6462302073,2944453.009291712],[364744.4265943199,2944457.805986403],[364767.32578000514,2944462.3548802836],[364786.11964407907,2944466.947866835],[364801.88404771156,2944471.987561134],[364815.1036183475,2944477.1911821854],[364821.66597954836,2944481.543422754],[364826.74388749583,2944486.3723540865],[364831.50824756135,2944494.078969089],[364834.0959974242,2944501.0371844904],[364835.2557326524,2944507.2063370505],[364835.2557326524,2944514.6705403468],[364835.2557326524,2944517.0630086693],[364835.2557326524,2944519.536019604],[364835.2557326524,2944520.5700417287],[364833.15574571333,2944520.5700417287],[364832.0450023417,2944520.5700417287],[364832.0450023417,2944520.5700417287],[364516.41281089187,2945011.8117792667]]],\"spatialReference\":{\"wkid\":4545}}";
        MapGeometry mapGeometry = OperatorImportFromJson.local().execute(Geometry.Type.Polygon, jsonString);
        Geometry geometry = mapGeometry.getGeometry();
        System.out.println(geometry.calculateArea2D());`
get -242764.5201788873

**Comment by stolstov** [comment]
@muyline This library returns positive area for polygons that have clockwise exterior rings. If this polygon has counterclockwise exterior it is going to have negative area.

**Comment by muyline** [comment]
> @muyline This library returns positive area for polygons that have clockwise exterior rings. If this polygon has counterclockwise exterior it is going to have negative area.

thanks
