### ISSUE TITLE
OGCGeometry#asGeoJson() makes Polygon outer ring to a counter clockwise direction

### ISSUE THREAD

**Issue by FalconIA** [Esri/geometry-api-java#221]
In doc [http://esri.github.io/geometry-api-java/doc/Polygon.html](http://esri.github.io/geometry-api-java/doc/Polygon.html) : **clockwise direction**.

![](http://esri.github.io/geometry-api-java/doc/Images/Polygon/Ring2.jpg)

After OGCGeometry#makeSimple() : **clockwise direction**.
`{"rings":[[[103.827535,25.533346],[103.827535,25.5338],[103.828293,25.5338],[103.828293,25.533346],[103.827535,25.533346]]]}`

Afer OGCGeometry#asGeoJson() : **counter clockwise direction**.
`{"type":"Polygon","coordinates":[[[103.827535,25.533346],[103.828293,25.533346],[103.828293,25.5338],[103.827535,25.5338],[103.827535,25.533346]]],"crs":{"type":"name","properties":{"name":"EPSG:4326"}}}`

**Comment by jgravois** [comment]
This is by design.

Unlike other specifications, RFC 7946 mandates GeoJSON use a counterclockwise ring winding order for exterior rings.

> A linear ring MUST follow the right-hand rule with respect to the
      area it bounds, i.e., exterior rings are counterclockwise, and
      holes are clockwise.

https://tools.ietf.org/html/rfc7946#section-3.1.6

**Comment by FalconIA** [comment]
Thanks a lot.
