### ISSUE TITLE
Documentation Bug - Polygon

### ISSUE THREAD

**Issue by APHawkes** [Esri/geometry-api-java#222]
In the section "Creating a polygon" > "Polygon class methods", there appears to be a missing line from the code. The outermost polygon is missing a point compared to the drawn shape in the image.

``` Java
public static Polygon createPolygon1()
{
    Polygon poly = new Polygon();

    // clockwise => outer ring
    poly.startPath(0, 0);
    poly.lineTo(-0.5, 0.5);
    // Missing poly.lineTo(0,1);
    poly.lineTo(0.5, 1);
    poly.lineTo(1, 0.5);
    poly.lineTo(0.5, 0);
```

**Comment by jgravois** [comment]
thanks for pointing that out @APHawkes!

if you've got the bandwidth/interest to open up a pull request, you can find the relevant line here:

https://github.com/Esri/geometry-api-java/blob/gh-pages/doc/Polygon.html#L206

**Comment by APHawkes** [comment]
https://github.com/Esri/geometry-api-java/pull/223

**Comment by jgravois** [comment]
awesome. thanks for your contribution!
