### ISSUE TITLE
DirtyFlags duplicate?

### ISSUE THREAD

**Issue by paulushub** [Esri/geometry-api-java#235]
It seems this interface  of constants is defined twice:
`com.esri.core.geometry.DirtyFlags` and 
`com.esri.core.geometry.MultiVertexGeometryImpl.DirtyFlags `

The only difference being the capitalization of the first character of the constant names: `DirtyIsKnownSimple` vs `dirtyIsKnownSimple`.

**Comment by stolstov** [comment]
@paulushub Thank you, I've removed the duplicate.

**Comment by paulushub** [comment]
Thank you.
