### ISSUE TITLE
Question: SizeOf Values

### ISSUE THREAD

**Issue by paulushub** [Esri/geometry-api-java#240]
How are the various object sizes in SizeOf computed? Is this affected by the type of the operating system (32-bit or 64-bit systems)?

**Comment by stolstov** [comment]
If you are porting to c#, you could use sizeof(T). Java does not have this so the values were hardcoded probably on 64 bit platform. @mbasmanova would know better.

**Comment by paulushub** [comment]
Thanks, the sizeof operator can only take the name of an **unmanaged** type; that is, a **struct type** whose fields are only integral types, Booleans, pointers and so on.
This does not apply here, so I have to loop through the fields of the various types and compute the sizes.

**Comment by mbasmanova** [comment]
@paulushub Paul, sizeOf implementation comes from airlift: https://github.com/airlift/slice/blob/master/src/main/java/io/airlift/slice/SizeOf.java

**Comment by stolstov** [comment]
@paulushub If you wish you could use Marshal.SizeOf on the 64 bit build to write down the constant values. These constants are used in the estimateMemorySize methods, that are documented to be approximate.

**Comment by paulushub** [comment]
@stolstov  and @mbasmanova Thanks so much for the updates and the supports.
I think you can close the thread - thank you.
