### ISSUE TITLE
OGCConcreteGeometryCollection.hashCode() computation

### ISSUE THREAD

**Issue by paulushub** [Esri/geometry-api-java#242]
The following implementation of the `hashCode()` is likely wrong:
```java
@Override
public int hashCode() {
	int hash = 1;
	if (geometries != null)
		hash = geometries.hashCode();
	
	if (esriSR != null)
		hash = NumberUtils.hashCombine(hash, esriSR.hashCode());
	
	return hash;
}
```
`geometries` used in the above code is a simple java list `List<OGCGeometry> geometries;` so the line `hash = geometries.hashCode();` is likely wrong. The hash code of the list should be the combination of hash codes of its members.

Also, I do know if you will find this useful: for my port, when the `OGCGeometry` is empty, I use the hash code from the `OGCGeometry.GeometryType` string. This I think will distinguish between empty polygon and point, for instance.

**Comment by stolstov** [comment]
https://docs.oracle.com/javase/7/docs/api/java/util/List.html#hashCode
