### ISSUE TITLE
there is implementation documentation for OperatorOffset

### ISSUE THREAD

**Issue by kunzhou5826** [Esri/geometry-api-java#244]
first, I would like to thank your for implementing such a great geometry lib. i used this lib for offsetting polygons with lots of points at specified distance. but in some cases, the offset just return a empty polygon. I try to look into the codes but it is not so easy to fully understand. I would like to know if we can know the details of the algorithm of offset or there is any reference papers. Thanks a lot.

**Comment by stolstov** [comment]
Usually, you should be using OperatorBuffer instead of OperatorOffset for polygons.
