### ISSUE TITLE
Trivial intersection yields invalid geometries

### ISSUE THREAD

**Issue by jagill** [Esri/geometry-api-java#245]
Given this polygon with a hole in it (https://gist.github.com/jagill/548cd665fbcdec83f68f51984208c748), intersecting it with a box much bigger than it yields a non-simple geometry.  The hole intersects the exterior at a single point; the intersection algorithm converts this into a self-intersection of the exterior:

```java
        String originalWkt = readResource("hole_intersection_bug.wkt");

        double xmin = -90.0;
        double ymin = 22.0;
        double xmax = -66.0;
        double ymax = 40.0;

        Envelope envelope = new Envelope(xmin, xmax, ymin, ymax);
        Polygon esriTilePolygon = new Polygon();
        esriTilePolygon.addEnvelope(envelope, false);
        OGCPolygon ogcTilePolygon = new OGCPolygon(esriTilePolygon, null);

        OGCGeometry original = OGCGeometry.fromText(originalWkt);
        assert(original.isSimple());
        OGCGeometry intersection = original.intersection(ogcTilePolygon);
        assert(intersection.isSimple()); // FAIL
```

Is this a bug, or is there something I'm missing?

**Comment by stolstov** [comment]
@jagill I'll look

**Comment by stolstov** [comment]
I see. We don't call makeSimple to enforce OGC simple on the result. It seems to be missing in all OGC Geometry operations. The isSimpleRelaxed would return true though.
Is it a valid workaround for you to call makeSimple when you require the isSimple = true?

**Comment by jagill** [comment]
How expensive is the isSimple() check, or calling makeSimple() when the geometry is already simple?  I ask because this is used in an engine for user queries that might be doing millions of intersections, and I'm worried about performance regressions.

**Comment by stolstov** [comment]
@jagill It goes though same code as the intersection method. Should be same as calling intersection.

If you know that you are testing extent against polygon,and polygons are usually smaller, then a fast extent check for containment would help to avoid calling intersection.

**Comment by jagill** [comment]
We can use `makeSimple`.  Is automatically correcting for simplicity in overlap operations (in the esri library proper) a good idea, or would that cause other problems?

**Comment by stolstov** [comment]
Yes it would be a good idea. Those OGC methods should produce OGC simple geometries.
