### ISSUE TITLE
Simple geometry reported as non-simple

### ISSUE THREAD

**Issue by jagill** [Esri/geometry-api-java#247]
We have many multilinestrings like the one below, which are "tadpole" shapes with a loop and a tail.  As a linestring they are invalid, but can be made valid by breaking them up into three line strings: two for the loop, and one for the tail, all intersecting only at boundary points.

Inspecting the multilinestring shows that it is simple.  However, Esri reports it as non-simple: it fails at the `checkCracking_()` at `OperatorSimplifyLocalHelper.isSimplePlanarImpl_` line 127.

```java
String wkt = "MULTILINESTRING ((-103.4894322 25.6164519, -103.4889647 25.6159054, -103.489434 25.615654), (-103.489434 25.615654, -103.4894322 25.6164519), (-103.4897361 25.6168342, -103.4894322 25.6164519))";
OGCGeometry ogcGeom = OGCGeometry.fromText(wkt);
assert(ogcGeom.isSimple()); // This fails!
```

**Comment by jagill** [comment]
cc @vladgp

**Comment by stolstov** [comment]
@jagill I'll take a look
