### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Esri/geometry-api-java#251]
https://github.com/Esri/geometry-api-java/blob/73a8be8d62f809b56ff432144aca468b3d1d9d2c/src/main/java/com/esri/core/geometry/OperatorFactoryLocal.java#L187
https://github.com/Esri/geometry-api-java/blob/73a8be8d62f809b56ff432144aca468b3d1d9d2c/src/main/java/com/esri/core/geometry/OperatorFactoryLocal.java#L281
The program can potentially fail to release a system resource.

**Comment by stolstov** [comment]
@QiAnXinCodeSafe Thank you for reporting this issue. Note that these methods are for debugging purposes only so this is of low concern. Would you like to submit a pull request with a fix?
