### ISSUE TITLE
Any util method for reading a GeoJson file?

### ISSUE THREAD

**Issue by gisfromscratch** [Esri/geometry-api-java#256]
I only found GeoJson import methods of the Geometry Engine. Is there any util method for reading a GeoJson file or Feature Collection in one shot?

**Comment by stolstov** [comment]
@gisfromscratch There is no such method here as there is no a concept of the Feature in this library.

In case someone wishes to contribute a way to read a bunch of geometries from a GeoJson feature collection, a right place to do so would be in the samples repository https://github.com/Esri/samples-geometry-api-java. Take a look into the Shapefile geometry cursor implementation.

**Comment by gisfromscratch** [comment]
Thank you. I am going to fork the samples repo.

**Comment by randallwhitman** [comment]
@gisfromscratch For ideas see also https://github.com/Esri/spatial-framework-for-hadoop/tree/master/json/src/main/java/com/esri/json
