### ISSUE TITLE
Are Multipolygons supported?

### ISSUE THREAD

**Issue by gisfromscratch** [Esri/geometry-api-java#257]
I created a GeoJson file containing Multipolygones. I ran into a _GeometryException: invalid shape type_. Is the MultiPolygone shape type currently supported?

**Comment by stolstov** [comment]
https://github.com/Esri/geometry-api-java/blob/37b7635d9c1f3d1f4119191272a8e8406a379d0d/src/test/java/com/esri/core/geometry/TestImportExport.java#L1277

**Comment by gisfromscratch** [comment]
@stolstov Works like a charme 👍 
[GeoJson Shell](https://github.com/gisfromscratch/spatial-spikes/blob/master/src/java/geojson.shell/src/geojson/shell/GeoJsonShell.java)
