### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by davidraleigh** [Esri/geometry-api-java#261]
Any interest in a gradle build file in addition to the maven?

Like this one: https://github.com/davidraleigh/geometry-api-java/blob/gradle/build.gradle

**Comment by stolstov** [comment]
@davidraleigh I think better place for this would be in the samples:
https://github.com/Esri/samples-geometry-api-java/

**Comment by davidraleigh** [comment]
That requires more of a write up kind of thing. No biggee. Just thought I'd offer since I was using gradle and had it working with Geometry.
