### ISSUE TITLE
Offline Routing in ESRI arcgis api for javascript

### ISSUE THREAD

**Issue by AminBangash** [Esri/geometry-api-java#263]
Is it some sample resource, how to calculate route between two points on map offline api for javascript.
My requirement is not to use arcgis online route service.

**Comment by randallwhitman** [comment]
This library is for *java* (JVM) ; the ArcGIS API for JavaScript/EcmaScript is separate.
You could try asking on GeoNet, GIS Stack-Exchange, etc.
