### ISSUE TITLE
Is there any way to create an outlined polygon based on multiple polygons?

### ISSUE THREAD

**Issue by QigangZhong** [Esri/geometry-api-java#265]
I would like to create a single polygon from two adjacent polygons that do not share any boundaries (there's a gap between the two polygons) so that I end up with one final polygon that encompasses both polygons and the space between them. OperatorUnion does not work for this scenario. Any suggestions?

**Comment by stolstov** [comment]
@QigangZhong We don't have any method specifically for this. Convex hull maybe, not sure if this is what you want. How do you define "space between polygons"?

**Comment by QigangZhong** [comment]
Not the convex hull, actually more like the outermost boundary of the given polygons. 
Like the red polygons in the following two images:

https://github.com/QigangZhong/gis-demos/blob/master/imgs/outline%20of%20polygons-1.jpg

https://github.com/QigangZhong/gis-demos/blob/master/imgs/outline%20of%20polygons-2.jpg

thx.

**Comment by stolstov** [comment]
@QigangZhong We don't have any function for this in the library. 

Here is a tool in Esri products that can do something like this: https://pro.arcgis.com/en/pro-app/tool-reference/cartography/aggregate-polygons.htm. You have to use ArcGIS Pro for this.
