### ISSUE TITLE
Disjoint vs. intersects efficiency?

### ISSUE THREAD

**Issue by DaveInCaz** [Esri/geometry-api-java#270]
On the documentation page http://esri.github.io/geometry-api-java/doc/Disjoint.html it says:

> Disjoint is the inverse of Intersects. Disjoint is the most efficient operator...

This is probably a fairly basic question, but just as a clarification: is `Intersects() `any less efficient than `Disjoint()`?

Depending on logical program flow it may be more natural to do 

`if(Intersects(...)) { ... }`

instead of

`if(!Disjoint(...)) { ... }`

unless there is a performance difference.

Thanks!

**Comment by stolstov** [comment]
@DaveInCaz Hello, the Intersects is implemented as Intersects() { return !Disjoint(); }.

**Comment by DaveInCaz** [comment]
@stolstov ha ha, thank you for a perfect answer 👍 

(I should have just looked in the code myself.)
