### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by DaveInCaz** [Esri/geometry-api-java#272]
Hello,

I noticed that in page http://esri.github.io/geometry-api-java/doc/Polygon.html in section "**Valid polygons**" the link "_Simplify operator with OGC restrictions_" results in an error (404).

It is linking to http://esri.github.io/geometry-api-java/doc/SimplifyOGC.html which seems to be invalid. I searched but couldn't find anything that seemed to be what was intended.

Thanks!

**Comment by alocke** [comment]
Hi,
Thanks for bringing this to our attention. It should be pointing to the API Reference page, 
http://esri.github.io/geometry-api-java/javadoc/com/esri/core/geometry/OperatorSimplifyOGC.html

You can find more information by downloading the OCG spec from 
https://www.ogc.org/standards/sfa

**Comment by DaveInCaz** [comment]
Thanks @alocke. I created a PR to fix the link - https://github.com/Esri/geometry-api-java/pull/273

I used HTTPS but otherwise it used the link you provided.

**Comment by alocke** [comment]
Thank you @DaveInCaz
