### ISSUE TITLE
OperatorExportToWkb throws GeometryException (corrupted geometry) for this geometry. 

### ISSUE THREAD

**Issue by alocke** [Esri/geometry-api-java#275]
Input geometry
![image](https://user-images.githubusercontent.com/4031186/95103543-93b21400-06e9-11eb-917f-9954974e7834.png)

```{"rings":[[[-122.25601,37.77901],[-122.25601,37.778488182101874],[-122.25601,37.77901]],[[-122.25601,37.7779960000231],[-122.25601,37.778023999676876],[-122.25596999966108,37.7781200003143],[-122.2555200002976,37.77799000006753],[-122.25538999970293,37.77815000001112],[-122.25601,37.77841303043591],[-122.25601,37.778488182101874],[-122.25594000042216,37.77858999984528],[-122.25527000005233,37.77832000019295],[-122.25516999959491,37.77844999985938],[-122.25583999996472,37.77874999991022],[-122.25574999955303,37.778869999731604],[-122.25508000008153,37.77859999968197],[-122.25498999999999,37.778709999522896],[-122.25498999999999,37.777989999999996],[-122.25599499996613,37.777989999999996],[-122.25601,37.7779960000231]],[[-122.25498999999999,37.77871000008598],[-122.25558999971946,37.77899999985086],[-122.25558461506371,37.77901],[-122.25526800070584,37.77901],[-122.25498999999999,37.77887761878223],[-122.25498999999999,37.77871000008598]]]}```

**Comment by stolstov** [comment]
The geometry in question is not a valid geometry for OGC. First ring is of zero area, and this was causing issue with determining where the OGC polygon starts.. The issue is fixed to have this exported despite being invalid polygon.
