### ISSUE TITLE
TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL inside JsonReaderCursor.java

### ISSUE THREAD

**Issue by blockcoder1** [Esri/geometry-api-java#292]
Hello Team,

I was just going through the code and found out that inside /esri/core/geometry/JsonReaderCursor.java we can see **TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL**. Just wanted to know now that project is open sourced is it still required? Can we remove it?

**Comment by stolstov** [comment]
@blockcoder1 Thank you for letting us know. This is a wrong comment. I have submitted a PR to remove it.

**Comment by blockcoder1** [comment]
@stolstov Thank you for a quick fix.
