### ISSUE TITLE
Transform geometry objects from one projection to another

### ISSUE THREAD

**Issue by kaushiksrini** [Esri/geometry-api-java#304]
Does this package allow for projections from one SRID to another? I can see there is a [ProjectionTransformation](https://github.com/Esri/geometry-api-java/blob/master/src/main/java/com/esri/core/geometry/ProjectionTransformation.java) package that is not implemented here. I am unable to find the function in the [GeometryEngine](https://esri.github.io/geometry-api-java/javadoc/com/esri/core/geometry/GeometryEngine.html) package, but I can see it available in this [project function](https://resources.arcgis.com/en/help/runtime-java/apiref/com/esri/core/geometry/GeometryEngine.html#project(com.esri.core.geometry.Geometry,%20com.esri.core.geometry.SpatialReference,%20com.esri.core.geometry.SpatialReference)) from arcgis software.

cross references - #212, #201

**Comment by randallwhitman** [comment]
It is not implemented, as stated in the cross-referenced issues.

**Comment by kaushiksrini** [comment]
Thanks for responding. Are there plans for it to be implemented, or taking contributions for it?

**Comment by stolstov** [comment]
@kaushiksrini We have no plans to provide projection functionality in this library at this moment. I don't think we can take a contribution of such functionality as a part of this package itself at this moment. It would have to be done in an external repository.

**Comment by randallwhitman** [comment]
Here is a more detailed discussion of projection/transformation in a related repo - https://github.com/Esri/spatial-framework-for-hadoop/issues/186

**Comment by stolstov** [comment]
close as designed
