### ISSUE TITLE
JsonWriter throws exception when started as an Array

### ISSUE THREAD

**Issue by abalog** [Esri/geometry-api-java#61]

**Comment by alocke** [comment]
@abalog Do you have a repro case for this?

**Comment by abalog** [comment]
JsonWriter writer = new JsonStringWriter();
writer.startArray();

**Comment by alocke** [comment]
Oh, easy enough. Thanks.

**Comment by alocke** [comment]
JsonWriter and JsonStringWriter are not public.

**Comment by abalog** [comment]
@alocke Then this can be closed.  The repo case is only for our full version which is used internally for tests that are not public.
