### ISSUE TITLE
Scala: Can not create Line using new Line() constructor 

### ISSUE THREAD

**Issue by manasdebashiskar** [Esri/geometry-api-java#63]
Hi, 
 I am trying to use ESRI api to create Line from two points using scala.
 If I try the following line
 val line = new Line() // same as trying "Line line = new Line() in java"
 I get a stack trace on my scala interpreter. 

I am using esri geometry api version = 1.2
When I create point or polygon I don't get any crash. Only when I try Line I get this stack trace.
The problem can't be as big as the constructor is bad; I think I am doing something wrong just can't figure out what?

The stack trace that I get is copied below:

_com.esri.core.geometry.GeometryException: invalid call
	_atcom.esri.core.geometry.JsonStringWriter.start_(JsonStringWriter.java:264)_
	_atcom.esri.core.geometry.JsonStringWriter.next_(JsonStringWriter.java:235)_
	_atcom.esri.core.geometry.JsonStringWriter.getJson(JsonStringWriter.java:30)_
	_atcom.esri.core.geometry.OperatorExportToJsonCursor.exportToString(OperatorExportToJsonCursor.java:65)_
	_atcom.esri.core.geometry.OperatorExportToJsonCursor.next(OperatorExportToJsonCursor.java:57)_
	_atcom.esri.core.geometry.OperatorExportToJsonLocal.execute(OperatorExportToJsonLocal.java:40)_
	_atcom.esri.core.geometry.Geometry.toString(Geometry.java:572)_
	_atscala.runtime.ScalaRunTime$.scala$runtime$ScalaRunTime$$inner$1(ScalaRunTime.scala:324)_
	_atscala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:329)_
	_atscala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:337)_
	_at.<init>(<console>:10)_
	_at.<clinit>(<console>)_
	_at$print(<console>)_
	_atsun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)_
	_atsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)_
	_atsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)_
	_atjava.lang.reflect.Method.invoke(Method.java:606)_
	_atscala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)_
	_atscala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)_
	_atscala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)_
	_atscala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)_
	_atscala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$DefaultBuilder$$anon$1.interpret(EclipseRepl.scala:152)_
	_atscala.tools.eclipse.interpreter.EclipseRepl.scala$tools$eclipse$interpreter$EclipseRepl$$doit(EclipseRepl.scala:233)_
	_atscala.tools.eclipse.interpreter.EclipseRepl.scala$tools$eclipse$interpreter$EclipseRepl$$add(EclipseRepl.scala:212)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$act$1$$anonfun$applyOrElse$1.apply(EclipseRepl.scala:266)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$act$1$$anonfun$applyOrElse$1.apply(EclipseRepl.scala:266)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$scala$tools$eclipse$interpreter$EclipseRepl$$safely$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(EclipseRepl.scala:252)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$scala$tools$eclipse$interpreter$EclipseRepl$$safely$1$$anonfun$apply$mcV$sp$1.apply(EclipseRepl.scala:252)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$scala$tools$eclipse$interpreter$EclipseRepl$$safely$1$$anonfun$apply$mcV$sp$1.apply(EclipseRepl.scala:252)_
	_atscala.util.DynamicVariable.withValue(DynamicVariable.scala:57)_
	_atscala.Console$.withErr(Console.scala:167)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$scala$tools$eclipse$interpreter$EclipseRepl$$safely$1.apply$mcV$sp(EclipseRepl.scala:251)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$scala$tools$eclipse$interpreter$EclipseRepl$$safely$1.apply(EclipseRepl.scala:251)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$scala$tools$eclipse$interpreter$EclipseRepl$$safely$1.apply(EclipseRepl.scala:251)_
	_atscala.util.DynamicVariable.withValue(DynamicVariable.scala:57)_
	_atscala.Console$.withOut(Console.scala:126)_
	_atscala.tools.eclipse.interpreter.EclipseRepl.scala$tools$eclipse$interpreter$EclipseRepl$$safely(EclipseRepl.scala:251)_
	_atscala.tools.eclipse.interpreter.EclipseRepl$$anonfun$act$1.applyOrElse(EclipseRepl.scala:266)_
	_atscala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)_
	_atscala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)_
	_atscala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)_
	_atscala.actors.ReactorTask.run(ReactorTask.scala:31)_
	_atscala.actors.Reactor$class.resumeReceiver(Reactor.scala:129)_
	_atscala.tools.eclipse.interpreter.EclipseRepl.scala$actors$InternalReplyReactor$$super$resumeReceiver(EclipseRepl.scala:177)_
	_atscala.actors.InternalReplyReactor$class.resumeReceiver(InternalReplyReactor.scala:59)_
	_atscala.tools.eclipse.interpreter.EclipseRepl.resumeReceiver(EclipseRepl.scala:177)_
	_atscala.actors.InternalActor$class.searchMailbox(InternalActor.scala:76)_
	_atscala.tools.eclipse.interpreter.EclipseRepl.searchMailbox(EclipseRepl.scala:177)_
	_atscala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Reactor.scala:117)_
	_atscala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:114)_
	_atscala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:114)_
	_atscala.actors.ReactorTask.run(ReactorTask.scala:33)_
	_atscala.actors.ReactorTask.compute(ReactorTask.scala:63)_
	_atscala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)_
	_atscala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)_
	_atscala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)_
	_atscala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)_
	_atscala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)_

Thanks
Manas

**Comment by alocke** [comment]
@stolstov Should the visibility of Line(VertexDescription vd) and Line(double x1, double y1, double x2, double y2) be public?

**Comment by alocke** [comment]
Verified fixed in master.

**Comment by stolstov** [comment]
@alocke It should. Next time.
