### ISSUE TITLE
How to use QuadTree 

### ISSUE THREAD

**Issue by manasdebashiskar** [Esri/geometry-api-java#65]
Hi, 
 This is more of a usability question than an issue. I could not find a documentation as to how to use QuadTree.
My tree creation function looks something like below -

def getQTree(grid : Array[(Int, Geometry)]) = {
    val quadTree = new QuadTree(new Envelope2D(-180, -90, 180, 90), 8)
    val g = grid.zipWithIndex.map(kv => (kv._2, kv._1._2))
    var hint = -1
    grid.foreach { kv=>
      var env = new Envelope2D
      kv._2.queryEnvelope2D(env)
      hint = quadTree.insert(kv._1, env, hint)
    }
    quadTree
}

In my above function grid is a quarter degree cells for the world for which I want to create an index.
Now that the tree is created how do I get back the list of elements for a given geometry?
Also how does the tolerance work in the functions "quadTree.getIterator(query, someTolerance)"

I could not find any documentation for the QuadTree except the mention of class name in the wiki.

Thanks
Manas

**Comment by randallwhitman** [comment]
Doc reference - https://github.com/Esri/geometry-api-java/wiki#tolerance
