### ISSUE TITLE
OperatorCut is returning incorrect result that has an extra piece. 

### ISSUE THREAD

**Issue by alocke** [Esri/geometry-api-java#80]
The input geometries look like this
![inputgeometries](https://cloud.githubusercontent.com/assets/4031186/6307332/d4104ace-b8ef-11e4-986a-7cdc475e4197.jpg)
After the cut, Part 1 should look like this
![correctpart1](https://cloud.githubusercontent.com/assets/4031186/6307358/e796e346-b8ef-11e4-8945-4eeab336a0c8.jpg)
But it looks like this
![incorrectpart1](https://cloud.githubusercontent.com/assets/4031186/6307366/f0069daa-b8ef-11e4-94c1-c3b36408bf12.jpg)

To reproduce, call OperatorCut with the geometries given below.

Polygon
```
{"rings":[[[-11604995.7656,8979981.3125],[-11367449.8649,8952923.2698],[-11417456.6674,8482935.2742],[-11604995.7656,8979981.3125]],[[-11413312.0818,8881319.661799997],[-11484157.3169,8872426.242700003],[-11434130.1311,8653413.995800003],[-11413312.0818,8881319.661799997]]],"spatialReference":{"wkid":102100,"latestWkid":3857}}
```
Polyline
```
{"paths":[[[-11671894.6618,9046978.563699998],[-11533321.8561,8971817.182099998],[-11367449.8649,8952923.2698],[-11594355.0515,8812292.009900004],[-11240774.4285,8776106.858400002]]],"spatialReference":{"wkid":102100,"latestWkid":3857}}
```

**Comment by stolstov** [comment]
@alocke That's the output is obtained for the tolerance value of 1e-10. However 3857 should have the tolerance of 0.001, so this thin part should be deleted. A bug is in wkid to tolerance mapping.

**Comment by alocke** [comment]
Tested the fix in dev1.2.1. Works.

**Comment by alocke** [comment]
Verified fixed in master.
