### ISSUE TITLE
ST_GeomFromGeoJson object passed into ST_Intersects always results True

### ISSUE THREAD

**Issue by uamadman** [Esri/geometry-api-java#81]
I am using the following header information to test the following select statements.
```
add jar
  ../lib/esri-geometry-api.jar
  ../lib/spatial-sdk-hadoop.jar;

create temporary function ST_Intersects as 'com.esri.hadoop.hive.ST_Intersects';
create temporary function ST_LineString as 'com.esri.hadoop.hive.ST_LineString';
create temporary function ST_GeomFromGeoJson as 'com.esri.hadoop.hive.ST_GeomFromGeoJson';
create temporary function ST_Polygon as 'com.esri.hadoop.hive.ST_Polygon';
```

The answer for both select statements is false:
```
SELECT ST_Intersects(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[2.449,4.865], [7.00000001,8.00000001]]}'),ST_GeomFromGeoJson('{"type": "Polygon", "coordinates": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}'));
returned true

SELECT ST_Intersects(ST_LineString(2.449,4.865, 7.00000001,8.00000001), ST_Polygon(1.00000001,1.00000001, 4.00000001,1.00000001, 4.00000001,4.00000001, 1.00000001,4.00000001));
returned false
```
The answer for both select statements is true:

```
SELECT ST_Intersects(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[1.00000001,1.00000001], [7.00000001,8.00000001]]}'),ST_GeomFromGeoJson('{"type": "Polygon", "coordinates": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}'));
returned true

SELECT ST_Intersects(ST_LineString(1.00000001,1.00000001, 7.00000001,8.00000001), ST_Polygon(1.00000001,1.00000001, 4.00000001,1.00000001, 4.00000001,4.00000001, 1.00000001,4.00000001));
returned true
```

Thoughts?

**Comment by uamadman** [comment]
This is what it took to read GeoJSON and get the correct response from intersect.

create temporary function ST_Intersects as 'com.esri.hadoop.hive.ST_Intersects';
create temporary function ST_LineString as 'com.esri.hadoop.hive.ST_LineString';
create temporary function ST_GeomFromGeoJson as 'com.esri.hadoop.hive.ST_GeomFromGeoJson';
create temporary function ST_Polygon as 'com.esri.hadoop.hive.ST_Polygon';
create temporary function ST_AsText as 'com.esri.hadoop.hive.ST_AsText';
create temporary function ST_GeomFromText as 'com.esri.hadoop.hive.ST_GeomFromText';
create temporary function ST_GeometryType as 'com.esri.hadoop.hive.ST_GeometryType';
create temporary function ST_LineFromWKB as 'com.esri.hadoop.hive.ST_LineFromWKB';
create temporary function ST_MPolyFromWKB as 'com.esri.hadoop.hive.ST_MPolyFromWKB';
create temporary function ST_AsBinary as 'com.esri.hadoop.hive.ST_AsBinary';

SELECT ST_Intersects(ST_LineFromWKB(ST_AsBinary(ST_GeomFromText(ST_AsText(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[2.449,4.865], [7.00000001,8.00000001]]}'))))),ST_MPolyFromWKB(ST_AsBinary(ST_GeomFromText(ST_AsText(ST_GeomFromGeoJson('{"type": "Polygon", "coordinates": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}'))))));

**Comment by stolstov** [comment]
@climbage 
@uamadman Direct geometry calls pass:
```
    	OGCGeometry g1 = OGCGeometry.fromGeoJson("{\"type\": \"LineString\", \"coordinates\": [[1.00000001,1.00000001], [7.00000001,8.00000001]]}");
    	OGCGeometry g2 = OGCGeometry.fromGeoJson("{\"type\": \"Polygon\", \"coordinates\": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}");
    	boolean res1 = g1.intersects(g2);
    	assertTrue(res1);
    	
    	OGCGeometry g3 = OGCGeometry.fromGeoJson("{\"type\": \"LineString\", \"coordinates\": [[2.449,4.865], [7.00000001,8.00000001]]}");
    	boolean res2 = g3.intersects(g2);
    	assertTrue(!res2);
    	
    	MapGeometry gg1 = OperatorImportFromGeoJson.local().execute(0, Geometry.Type.Unknown, "{\"type\": \"LineString\", \"coordinates\": [[2.449,4.865], [7.00000001,8.00000001]]}", null);
    	MapGeometry gg2 = OperatorImportFromGeoJson.local().execute(0, Geometry.Type.Unknown, "{\"type\": \"Polygon\", \"coordinates\": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}", null);

    	boolean res3 = OperatorIntersects.local().execute(gg1.getGeometry(), gg2.getGeometry(), null, null);
    	assertTrue(!res3);
```

**Comment by stolstov** [comment]
Also tried to reload as esri shape, still worked:
```
    	OGCGeometry gb1 = OGCGeometry.fromBinary(OGCGeometry.fromGeoJson("{\"type\": \"LineString\", \"coordinates\": [[2.449,4.865], [7.00000001,8.00000001]]}").asBinary());
    	OGCGeometry gb2 = OGCGeometry.fromBinary(OGCGeometry.fromGeoJson("{\"type\": \"Polygon\", \"coordinates\": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}").asBinary());
    	boolean resb2 = gb1.intersects(gb2);
    	assertTrue(!resb2);
```

@randallwhitman @climbage

**Comment by climbage** [comment]
@uamadman This is more likely an issue in the Hive UDF side of things.  Where did you get the spatial SDK jar?

**Comment by randallwhitman** [comment]
With spatial-framework-for-hadoop master and geometry-api-java master, I get results false, false, true, true (in hive-.14 on hadoop-2.2).

The geometry JAR from 2014/08 in gis-tools-for-hadoop:samples/lib/ predates many fixes to geometry.  Cross reference https://github.com/Esri/gis-tools-for-hadoop/issues/21#issuecomment-66163082, https://github.com/Esri/spatial-framework-for-hadoop/issues/63#issuecomment-52576945

**Comment by uamadman** [comment]
I am using the spatial-framework-for-hadoop from samples/lib/ and the the geometry-api-java-1.2.1 from /geometry-api-java/releases.
I have attempted the above though HUE and a script via hive -i GeoJsontest.sql

I have attached two images showing my direct usage though hive and the results returned.
![geomfromgeojson](https://cloud.githubusercontent.com/assets/8550796/6831765/cb053372-d2f8-11e4-885a-74762e5088d1.png)
![st_line_polygon](https://cloud.githubusercontent.com/assets/8550796/6831766/cb060748-d2f8-11e4-9ad1-31eca54f077e.png)

(HIVE-.13.1, Hadoop 2.5.0-cdh5.3.0)

I am open and willing to try any ideas to make this function properly.

**Comment by stolstov** [comment]
@uamadman What you get for?
```
ST_AsText(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[2.449,4.865], [7.00000001,8.00000001]]}'))
ST_AsText(ST_GeomFromGeoJson('{"type": "Polygon", "coordinates": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}'))
```
Also ST_AsJson?

**Comment by uamadman** [comment]
For ST_AsText:
SELECT ST_AsText(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[2.449,4.865], [7.00000001,8.00000001]]}')); -- LINESTRING (2.449 4.865, 7.00000001 8.00000001)
SELECT ST_AsText(ST_GeomFromGeoJson('{"type": "Polygon", "coordinates": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}')); -- POLYGON ((1.00000001 1.00000001, 4.00000001 1.00000001, 4.00000001 4.00000001, 1.00000001 4.00000001, 1.00000001 1.00000001))

And for ST_AsJson:
SELECT ST_AsJson(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[2.449,4.865], [7.00000001,8.00000001]]}')); -- {"paths":[[[2.449,4.865],[7.00000001,8.00000001]]],"spatialReference":{"wkid":4326}}
SELECT ST_AsJson(ST_GeomFromGeoJson('{"type": "Polygon", "coordinates": [[[1.00000001,1.00000001], [4.00000001,1.00000001], [4.00000001,4.00000001], [1.00000001,4.00000001]]]}')); -- {"rings":[[[1.00000001,1.00000001],[1.00000001,4.00000001],[4.00000001,4.00000001],[4.00000001,1.00000001],[1.00000001,1.00000001]]],"spatialReference":{"wkid":4326}}

**Comment by randallwhitman** [comment]
In samples/lib spatial-sdk-hadoop.jar predates a [caching fix](https://github.com/Esri/spatial-framework-for-hadoop/issues/65) which could be at issue.
It would be best to try with an updated spatial-framework-for-hadoop.

**Comment by uamadman** [comment]
It appears getting my hands on that .jar without compiling it myself will be troublesome. @randallwhitman - Any chance you would be willing to update samples/lib/spatial-framework-for-hadoop.jar to accompany the esri-geometry-api-1.2.1 release?

**Comment by randallwhitman** [comment]
In fact, I've filed [an issue towards that](https://github.com/Esri/spatial-framework-for-hadoop/issues/76).  (@uamadman)

**Comment by uamadman** [comment]
With courage I accepted the challenge of compiling the Spatial Framework.

```
[INFO] Spatial Framework for Hadoop ....................... SUCCESS [  7.985 s]
[INFO] Hive Spatial Framework ............................. SUCCESS [02:10 min]
[INFO] Spatial JSON Utilities ............................. FAILURE [  9.196 s]
```
It appears there is a name change 
```
spatial-sdk-hive-1.0.3-SNAPSHOT.jar
```

Sadly... This does not appear to fix my issue :(
I restarted the entire cluster just to be sure.

ST_Intersection -- test 2 Returns the first geometry when fed GeoJson
```
SELECT ST_AsText(ST_Intersection(ST_GeomFromText('LINESTRING (1.5 1.5, 7.00000001 8.00000001, 8.00000001 10.00000001)'),
                                 ST_GeomFromText('LINESTRING (1.5 1.5, 7.00000001 8.00000001, 9.00000001 11.00000001)'))); 
                                 -- LINESTRING (1.5 1.5, 7.00000001 8.00000001)
                                 
SELECT ST_AsText(ST_Intersection(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[1.5,1.5], [7.00000001,8.00000001], [9.00000001,11.00000001]]}'),
                                 ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[1.5,1.5], [7.00000001,8.00000001], [8.00000001,10.00000001]]}'))); 
                                 --LINESTRING (1.5 1.5, 7.00000001 8.00000001, 9.00000001 11.00000001)
                               
SELECT ST_AsText(ST_Intersection(ST_GeomFromText('linestring(0 2, 0 0, 2 0)'),
                                 ST_GeomFromText('linestring(0 3, 0 1, 1 0, 3 0)')));
                                 --MULTILINESTRING ((1 0, 2 0), (0 2, 0 1))
```


ST_Intersects

All True
```
SELECT ST_Intersects(ST_GeomFromText('LINESTRING (1.5 1.5, 7.00000001 8.00000001, 8.00000001 10.00000001)'),
                     ST_GeomFromText('LINESTRING (1.5 1.5, 7.00000001 8.00000001, 9.00000001 11.00000001)'));
                     -- true

SELECT ST_Intersects(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[1.5,1.5], [7.00000001,8.00000001], [9.00000001,11.00000001]]}'),
                     ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[1.5,1.5], [7.00000001,8.00000001], [8.00000001,10.00000001]]}'));
                     -- true

SELECT ST_Intersects(ST_GeomFromText('linestring(0 2, 0 0, 2 0)'),
                     ST_GeomFromText('linestring(0 3, 0 1, 1 0, 3 0)'));
                     -- true
```

All False
```
SELECT ST_Intersects(ST_GeomFromText('LINESTRING (2.5 2.5, 8.00000001 9.00000001)'),
                     ST_GeomFromText('LINESTRING (1.5 1.5, 7.00000001 8.00000001)'));
                     -- false

SELECT ST_Intersects(ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[2.5,2.5], [8.00000001,9.00000001]]}'),
                     ST_GeomFromGeoJson('{"type": "LineString", "coordinates": [[1.5,1.5], [7.00000001,8.00000001]]}'));
                     -- true

SELECT ST_Intersects(ST_GeomFromText('linestring(1 1, 2 1, 3 1, 4 1)'),
                     ST_GeomFromText('linestring(1 0, 2 0, 3 0, 4 0)'));
                     -- false
```

Thoughts?

**Comment by randallwhitman** [comment]
@uamadman Let's continue in the spatial-framework-for-hadoop repository:
https://github.com/Esri/spatial-framework-for-hadoop/issues/77

**Comment by randallwhitman** [comment]
This issue is superseded by the issue on Spatial Framework for Hadoop.
