### ISSUE TITLE
envelope crossing date-line

### ISSUE THREAD

**Issue by lukepatrick** [Esri/geometry-api-java#83]
It doesn't seem an envelope can cross the date line.
I want to construct an envelope and see if it contains certain points. It's possible the envelope crosses the International date line.

Here is some sample code I've tried:
```java
    double lon = Double.parseDouble("179.99");
    double lat = Double.parseDouble("0");
    Point pt = new Point(lon, lat);

    double minlon = Double.parseDouble("170");
    double minlat = Double.parseDouble("-20");

    double maxlon = Double.parseDouble("-170");
    double maxlat = Double.parseDouble("20");

    Envelope ev = new Envelope(minlon, minlat, maxlon, maxlat);

    SpatialReference sr = SpatialReference.create(4326); // decimal degrees

    boolean test = GeometryEngine.contains(ev, pt, sr);

    System.out.println(GeometryEngine.geometryToJson(sr, ev));
    assertTrue("envelope containts point true", test);
```
The test fails, and if I check the print statement I get a json that has swapped my x-coordinates
```json
{"xmin":-170,"ymin":-20,"xmax":170,"ymax":20,"spatialReference":{"wkid":4326}}
```
Is there a different/better way to do this?

**Comment by stolstov** [comment]
@lukepatrick Envelope must have maxX >= minX, and maxY >= minY. Set maxlon to 190 and it'll work. Right now relational operations work in 2D plane, and spatial reference information is there only to tag and to provide tolerance value for calculations.

**Comment by lukepatrick** [comment]
Is there another way to accomplish a point-contained-in-an-envelope query with the api? Sure, I could change -170 to +190, but if I have a nearby similar point to query, -179 longitude, that would fall out.

**Comment by abalog** [comment]
@lukepatrick You could center your point so that it is within the xmin/xmax of your envelope, as long as you only move the point by +-360.

**Comment by stolstov** [comment]
@lukepatrick Move point by 360.
Some dirty pseudocode, assuming envelope is correct (xmax >= xmin):
```
bool ContainsWrapped(Geometry geom, Point pt)
{
Envelope env = new Envelope();
geom.queryEnvelope(env);
if (!(env.ymax >= pt.y && env.ymin >= pt.y))
  return false;

//Prepare the point for the test
while (pt.x > env.xmin)
  pt.x -= 360;

//Do the test:
while (pt.x <= env.xmax)
{
  if (contains(geom, pt, sr))
    return true;

  pt.x += 360;
}

return false;
}
```
