### ISSUE TITLE
How to get Geometry object by selecting shape column from oracle?

### ISSUE THREAD

**Issue by FalconIA** [Esri/geometry-api-java#97]
I am trying to get Geometry object directly from sql.

I use this sql:

    select shape from table;

Then try to get Geometry object by these codes:

    //ResultSet rs, String columnName
    byte[] bytes = rs.getBytes(columnName);
    ByteBuffer buffer = ByteBuffer.wrap(bytes);
    OperatorImportFromESRIShape op = (OperatorImportFromESRIShape) OperatorFactoryLocal.getInstance().getOperator(Operator.Type.ImportFromESRIShape);
    Geometry g = op.execute(0, Geometry.Type.Unknown, buffer);

But result is null.
Please show me a way how to get Geometry object directly from sql.

Thanks
Gavin Men

**Comment by stolstov** [comment]
@FalconlA What format the geometry is stored in? Are you sure it is esrishape? Have you tried OperatorImportFromWkb?

**Comment by FalconIA** [comment]
@stolstov The geometry is stored in ESRI Shape format (ArcGIS/ArcSDE).

If I use this sql, I could get the wkb formated data.

    select SDE.ST_AsBinary(shape) AS shape from table_name;

Is there any way directly to get ESRIShape bytes from sql, and import using OperatorImportFromESRIShape?

Thanks

**Comment by stolstov** [comment]
@FalconIA ST_AsBinary returns wkb. Try OperatorImportFromWkb.

**Comment by stolstov** [comment]
@FalconIA I am could not find any SDE.ST_XXXX method that would return an ESRI shape. I only see ST_AsText and ST_AsBinary. As far as I know, ArcSDE does not store geometries in ESRI Shape format.

**Comment by FalconIA** [comment]
@stolstov 
Ok, i got it. ArcSDE geometries ESRI Shape format, just the column called SHAPE.
I will use OperatorImportFromWkb instead.

Thanks
